[package]

name = "mod_conf"
version = "0.0.2"

[lib]
name = "mod_conf"
crate-type = ["dylib"]

[dependencies]
libc = "*"
interpolate_idents = "*"
lazy_static = "*"

[dependencies.apache2]
path = "../.."
