[package]

name = "mod_redis_log"
version = "0.0.2"

[lib]
name = "mod_redis_log"
crate-type = ["dylib"]

[dependencies.apache2]
path = "../.."

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"
